set_property SRC_FILE_INFO {cfile:/home/shomeb/u/ulrichji/Documents/dmpro/test_ebi/test_ebi.srcs/constrs_1/new/constraints.xdc rfile:../../../test_ebi.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D4    IOSTANDARD LVCMOS33 } [get_ports { clk }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T10 IOSTANDARD LVCMOS33 } [get_ports { EBId[0] }]; #IO_L6N_T0_VREF_15 Sch=EBIa[0]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E12 IOSTANDARD LVCMOS33 } [get_ports { EBId[1] }]; #IO_L13P_T2_MRCC_15 Sch=EBIa[1]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D13 IOSTANDARD LVCMOS33 } [get_ports { EBId[2] }]; #IO_L12P_T1_MRCC_15 Sch=EBIa[2]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C12 IOSTANDARD LVCMOS33 } [get_ports { EBId[3] }]; #IO_L11N_T1_SRCC_15 Sch=EBIa[3]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C14 IOSTANDARD LVCMOS33 } [get_ports { EBId[4] }]; #IO_L8P_T1_AD10P_15 Sch=EBIa[4]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A13 IOSTANDARD LVCMOS33 } [get_ports { EBId[5] }]; #IO_L7N_T1_AD2P_15 Sch=EBIa[5]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B14 IOSTANDARD LVCMOS33 } [get_ports { EBId[6] }]; #IO_L8N_T1_AD10N_15 Sch=EBIa[6]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A15 IOSTANDARD LVCMOS33 } [get_ports { EBId[7] }]; #IO_L9N_T1_DQS_AD3N_15 Sch=EBIa[7]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E11 IOSTANDARD LVCMOS33 } [get_ports { EBId[8] }]; #IO_L14P_T2_SRCC_15 Sch=EBIa[8]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E13 IOSTANDARD LVCMOS33 } [get_ports { EBId[9] }]; #IO_L13N_T2_MRCC_15 Sch=EBIa[9]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [get_ports { EBId[10] }]; #IO_L11P_T1_SRCC_15 Sch=EBIa[10]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C13 IOSTANDARD LVCMOS33 } [get_ports { EBId[11] }]; #IO_L12N_T1_MRCC_15 Sch=EBIa[11]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C16 IOSTANDARD LVCMOS33 } [get_ports { EBId[12] }]; #IO_L10P_T1_AD11P_15 Sch=EBIa[12]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A14 IOSTANDARD LVCMOS33 } [get_ports { EBId[13] }]; #IO_L7N_T1_AD2N_15 Sch=EBIa[13]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B15 IOSTANDARD LVCMOS33 } [get_ports { EBId[14] }]; #IO_L9P_T1_DQS_AD3P_15 Sch=EBIa[14]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B16 IOSTANDARD LVCMOS33 } [get_ports { EBId[15] }]; #IO_L10N_T1_AD11N_15 Sch=EBIa[15]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H13 IOSTANDARD LVCMOS33 } [get_ports { EBId[0] }]; #IO_L20N_T3_A19_15 Sch=EBId[0]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H11 IOSTANDARD LVCMOS33 } [get_ports { EBId[1] }]; #IO_L19P_T3_A22_15 Sch=EBId[1]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G14 IOSTANDARD LVCMOS33 } [get_ports { EBId[2] }]; #IO_L21P_T3_DQS_15 Sch=EBId[2]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F13 IOSTANDARD LVCMOS33 } [get_ports { EBId[3] }]; #IO_L16N_T2_A27_15 Sch=EBId[3]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS33 } [get_ports { EBId[4] }]; #IO_L22P_T3_A17_15 Sch=EBId[4]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D14 IOSTANDARD LVCMOS33 } [get_ports { EBId[5] }]; #IO_L15P_T2_DQS_15 Sch=EBId[5]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS33 } [get_ports { EBId[6] }]; #IO_L18P_T2_A24_15 Sch=EBId[6]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E16 IOSTANDARD LVCMOS33 } [get_ports { EBId[7] }]; #IO_L17P_T2_A26_15 Sch=EBId[7]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H12 IOSTANDARD LVCMOS33 } [get_ports { EBId[8] }]; #IO_L20P_T3_A20_15 Sch=EBId[8]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G12 IOSTANDARD LVCMOS33 } [get_ports { EBId[9] }]; #IO_L19N_T3_A21_VREF_15 Sch=EBId[9]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F12 IOSTANDARD LVCMOS33 } [get_ports { EBId[10] }]; #IO_L16P_T2_A28_15 Sch=EBId[10]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F14 IOSTANDARD LVCMOS33 } [get_ports { EBId[11] }]; #IO_L21N_T3_DQS_A18_15 Sch=EBId[11]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS33 } [get_ports { EBId[12] }]; #IO_L18N_T2_A23_15 Sch=EBId[12]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D15 IOSTANDARD LVCMOS33 } [get_ports { EBId[13] }]; #IO_L15N_T2_DQS_ADV_B_15 Sch=EBId[13]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G16 IOSTANDARD LVCMOS33 } [get_ports { EBId[14] }]; #IO_L22N_T3_A16_15 Sch=EBId[14]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D16 IOSTANDARD LVCMOS33 } [get_ports { EBId[15] }]; #IO_L17N_T2_A25_15 Sch=EBId[15]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 } [get_ports { EBId[0] }]; #IO_L23P_T3_FOE_B_15 Sch=EBIcs1
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J16 IOSTANDARD LVCMOS33 } [get_ports { EBId[1] }]; #IO_L23N_T3_FWE_B_15 Sch=EBIwen
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H14 IOSTANDARD LVCMOS33 } [get_ports { EBId[2] }]; #IO_L24P_T3_RS1_15 Sch=EBIren
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15 IOSTANDARD LVCMOS33 } [get_ports { EBId[3] }]; #IO_L24N_T3_RS0_15 Sch=EBIcs0
