# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/shomeb/u/ulrichji/Documents/dmpro/ulpi_test/ULPI_test/ULPI_test.cache/wt [current_project]
set_property parent.project_path /home/shomeb/u/ulrichji/Documents/dmpro/ulpi_test/ULPI_test/ULPI_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib /home/shomeb/u/ulrichji/Documents/dmpro/ulpi_test/ULPI_test/ULPI_test.srcs/sources_1/new/TopUlpiTest.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/shomeb/u/ulrichji/Documents/dmpro/ulpi_test/ULPI_test/ULPI_test.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/shomeb/u/ulrichji/Documents/dmpro/ulpi_test/ULPI_test/ULPI_test.srcs/constrs_1/new/constraints.xdc]


synth_design -top TopUlpiTest -part xc7a35tftg256-2


write_checkpoint -force -noxdef TopUlpiTest.dcp

catch { report_utilization -file TopUlpiTest_utilization_synth.rpt -pb TopUlpiTest_utilization_synth.pb }
