# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/shomeb/u/ulrichji/Documents/dmpro/upload_test/UploadTest/UploadTest.cache/wt [current_project]
set_property parent.project_path /home/shomeb/u/ulrichji/Documents/dmpro/upload_test/UploadTest/UploadTest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/shomeb/u/ulrichji/Documents/dmpro/upload_test/Arty_sw_btn_led/sw_btn_led.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/shomeb/u/ulrichji/Documents/dmpro/upload_test/Arty_sw_btn_led/Arty_sw_btn_Demo.xdc
set_property used_in_implementation false [get_files /home/shomeb/u/ulrichji/Documents/dmpro/upload_test/Arty_sw_btn_led/Arty_sw_btn_Demo.xdc]


synth_design -top sw_btn_led -part xc7a35tcsg324-1


write_checkpoint -force -noxdef sw_btn_led.dcp

catch { report_utilization -file sw_btn_led_utilization_synth.rpt -pb sw_btn_led_utilization_synth.pb }
