# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/shomeb/u/ulrichji/Documents/dmpro/input_test/vivado_project/input_test/input_test.cache/wt [current_project]
set_property parent.project_path /home/shomeb/u/ulrichji/Documents/dmpro/input_test/vivado_project/input_test/input_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_verilog -library xil_defaultlib /home/shomeb/u/ulrichji/Documents/dmpro/input_test/ulpi_wrapper/rtl/ulpi_wrapper.v
read_vhdl -library xil_defaultlib {
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/fpga-usb-serial-20131205/usb_transact.vhdl
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/fpga-usb-serial-20131205/usb_pkg.vhdl
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/fpga-usb-serial-20131205/usb_packet.vhdl
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/fpga-usb-serial-20131205/usb_init.vhdl
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/fpga-usb-serial-20131205/usb_control.vhdl
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/fpga-usb-serial-20131205/usb_serial.vhdl
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/fpga-usb-serial-20131205/usbtest.vhdl
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/src/TopModule.vhd
  /home/shomeb/u/ulrichji/Documents/dmpro/input_test/vivado_project/input_test/input_test.srcs/sources_1/new/InputModule.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/shomeb/u/ulrichji/Documents/dmpro/input_test/constraints/constraints.xdc
set_property used_in_implementation false [get_files /home/shomeb/u/ulrichji/Documents/dmpro/input_test/constraints/constraints.xdc]


synth_design -top TopModule -part xc7a35tftg256-2


write_checkpoint -force -noxdef TopModule.dcp

catch { report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb }
